server:
  port: 11115
spring:
  application:
    name: usergoal_service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: usergoalservice

  flyway:
    enabled: true
    schemas: usergoalservice
    default-schema: usergoalservice
    baseline-on-migrate: true

#   Google Vertex AI 및 벡터 스토어 설정
#  ai:
#    vertex:
#      ai:
#        gemini:
#          project-id: ${GEMINI_PROJECT_ID}
#          location: us-west1
#        vectorstore:
#          pgvector:
#            index-type: HNSW
#            distance-type: COSINE_DISTANCE
#            dimensions: 3072
#
### 별도 gemini 관련 일반 설정
##gemini:
#  project-id: ${GEMINI_PROJECT_ID}
#  embedding-model: gemini-embedding-001

## 1. Ollama 설정 (EXAONE-Deep 7.8B)
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#  # Chat (AI 분석) 모델
#      chat:
#        options:
#          # Chat 추론 모델 설정
#          model: exaone-deep:7.8b
#          temperature: 0.7
#  # Embedding (벡터 생성) 모델
#      embedding:
#        options:
##          임베딩 모델 설정 (VectorStore에서 사용)
#          model: exaone-deep:7.8b

  kafka:
    bootstrap-servers: 34.22.87.75:9092, 34.22.87.75:9093, 34.22.87.75:9094 # Kafka 브로커(또는 클러스터) 접속 주소와 포트, 쉼표(,)로 복수 브로커 지정 가능
    consumer:
      group-id: ai-group # 컨슈머 그룹 ID: 같은 그룹에 속한 컨슈머들은 파티션을 분담하여 처리
      auto-offset-reset: earliest # 컨슈머가 처음 시작할 때 오프셋이 없으면 어디서부터 읽을지 설정, earliest: 가장 오래된(처음) 메세지부터, latest: 최신 메세지 부터
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 메시지 키 역직렬화기(문자열로 디코딩)
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 메시지 값 역직렬화기(JSON -> 객체)
      properties:
        spring.json.trusted.packages: '*' # JsonDeserializer가 신뢰할 패키지 목록, '*' 모든 패키지를 신뢰(보안상 취약해 지므로 가능한 경우 패키지를 명시)
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.nextme.userGoal_service.userGoal.domain.entity.ChatMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 메시지 키 직렬화
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 메시지 값 직렬화(객체 -> JSON)
      properties:
        spring.json.add.type.headers: false
  #GPT
  ai:
    openai:
      api-key: ${API_KEY}          # LLM용 OpenAI API 키
      model: gpt-5-nano
      embedding:
        api-key: ${API_KEY}        # 임베딩용 OpenAI API 키
        model: text-embedding-3-small
    vectorstore:
      pgvector:
        enabled: false

  config:
    import: 'optional:configserver:'
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server

rag:
  embedding-model: text-embedding-3-small



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE}



# OPEN DOC API 설정
springdoc:
  version: '1.0.0'
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: full
  paths-to-match:
    - /**

openapi:
  service:
    url: ${OPENAPI_URL}

