server:
  port: 8081
spring:
  application:
    name: userGoal_service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#   Google Vertex AI 및 벡터 스토어 설정
#  ai:
#    vertex:
#      ai:
#        gemini:
#          project-id: ${GEMINI_PROJECT_ID}
#          location: us-west1
#        vectorstore:
#          pgvector:
#            index-type: HNSW
#            distance-type: COSINE_DISTANCE
#            dimensions: 3072
#
### 별도 gemini 관련 일반 설정
##gemini:
#  project-id: ${GEMINI_PROJECT_ID}
#  embedding-model: gemini-embedding-001

## 1. Ollama 설정 (EXAONE-Deep 7.8B)
  ai:
    ollama:
      base-url: http://localhost:11434
  # Chat (AI 분석) 모델
      chat:
        options:
          # Chat 추론 모델 설정
          model: exaone-deep:7.8b
          temperature: 0.7
  # Embedding (벡터 생성) 모델
      embedding:
        options:
#          임베딩 모델 설정 (VectorStore에서 사용)
          model: exaone-deep:7.8b


  rabbitmq:
    host: localhost #RabbitMQ host ip
    port: 5672 #RabbitMQ port
    username: guest #RabbitMQ 웹 관리 콘솔 아이디
    password: guest #RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: nextme-queue #사용할 queue 이름
  exchange:
    name: nextme-exchange #사용할 exchange 이름
  routing:
    key: key
